spring:
  application:
    name: consumer

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
      
ribbon:
  eureka:
    enabled: true
