spring:  application:    name: service-provider
server:
  port: 9000
  
eureka:  instance:    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  